name: MeowApp
options:
  bundleIdPrefix: com.alekdob
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: FC38UVV3V3
    CODE_SIGN_STYLE: Automatic

targets:
  MeowApp:
    type: application
    platform: [iOS, macOS]
    sources:
      - path: Sources
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.alekdob.MeowApp
        PRODUCT_NAME: MeowApp
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        CODE_SIGN_ENTITLEMENTS: MeowApp.entitlements
    info:
      path: Sources/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~iphone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSFaceIDUsageDescription: "Unlock MeowApp with Face ID"
        NSSpeechRecognitionUsageDescription: "Meow uses speech recognition for voice input"
        NSMicrophoneUsageDescription: "Meow needs the microphone for voice input"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: SwiftData.framework
      - sdk: LocalAuthentication.framework
      - target: MeowShareExtension
        platforms: [iOS]

  MeowShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ShareExtension
        excludes:
          - "**/.DS_Store"
          - Info.plist
      - path: Sources/Core/Auth/SharedConfig.swift
      - path: Sources/Core/Persistence/PendingShareQueue.swift
      - path: Sources/Core/Design/MeowTheme.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.alekdob.MeowApp.ShareExtension
        PRODUCT_NAME: MeowShare
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: ShareExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: ShareExtension/MeowShareExtension.entitlements
    entitlements:
      path: ShareExtension/MeowShareExtension.entitlements

schemes:
  MeowApp_iOS:
    build:
      targets:
        MeowApp_iOS: all
    run:
      config: Debug
    profile:
      config: Release
    archive:
      config: Release
  MeowApp_macOS:
    build:
      targets:
        MeowApp_macOS: all
    run:
      config: Debug
    profile:
      config: Release
    archive:
      config: Release
